name: 'deploy docker'

on:
  push:
    tags:
      - "*"

jobs:

  release-docker-image-job:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: 'node-app'
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref_name }}'
    steps:
      - name: Convert variables to lowercase
        run: |
          export LOWERCASE_CONTAINER_NAME=$(echo "${{ env.CONTAINER_NAME }}" | tr '[:upper:]' '[:lower:]')
          export LOWERCASE_DOCKER_IMAGE_URL=$(echo "${{ env.DOCKER_IMAGE_URL }}" | tr '[:upper:]' '[:lower:]')
          echo "Lowercase Docker Image URL: $LOWERCASE_DOCKER_IMAGE_URL"
          echo "Lowercase Container Name: $LOWERCASE_CONTAINER_NAME"

      - name: Execute SSH commands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'superuser@123.253.62.249'
          privateKey: ${{ secrets.My_PRIVATE_KEY }}
          command: |
            sudo docker logout ghcr.io
            sudo docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}
            sudo docker rm -f $LOWERCASE_CONTAINER_NAME
            sudo docker pull $LOWERCASE_DOCKER_IMAGE_URL
            sudo docker run --restart=always -d --name $LOWERCASE_CONTAINER_NAME -p 9066:3000 $LOWERCASE_DOCKER_IMAGE_URL
      


            